package entrypoint

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/abyssmemes/contextverse/internal/logx"
)

// Options control entry-point generation into a project working directory.
type Options struct {
	SpaceRoot string
	TargetDir string // usually cwd
	Project   string // optional active project name under projects/
	Silent    bool
}

// Result lists files written.
type Result struct {
	Files []string
}

// Generate writes thin pointer files for Claude and Cursor into TargetDir.
func Generate(opts Options) (*Result, error) {
	if opts.SpaceRoot == "" {
		return nil, fmt.Errorf("space root is required")
	}
	if opts.TargetDir == "" {
		return nil, fmt.Errorf("target directory is required")
	}
	log := logx.L()

	absSpace, err := filepath.Abs(opts.SpaceRoot)
	if err != nil {
		return nil, fmt.Errorf("resolve space root: %w", err)
	}
	absTarget, err := filepath.Abs(opts.TargetDir)
	if err != nil {
		return nil, fmt.Errorf("resolve target dir: %w", err)
	}

	if _, err := os.Stat(filepath.Join(absSpace, "context-entry.md")); err != nil {
		return nil, fmt.Errorf("space looks uninitialized at %s (missing context-entry.md): %w", absSpace, err)
	}

	res := &Result{}

	claudePath := filepath.Join(absTarget, "CLAUDE.md")
	if err := os.WriteFile(claudePath, []byte(claudeMD(absSpace, opts.Project)), 0o644); err != nil {
		return nil, fmt.Errorf("write CLAUDE.md: %w", err)
	}
	res.Files = append(res.Files, claudePath)
	log.Info("wrote entry point", "path", claudePath)

	rulesDir := filepath.Join(absTarget, ".cursor", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		return nil, fmt.Errorf("create .cursor/rules: %w", err)
	}
	cursorPath := filepath.Join(rulesDir, "contextverse.mdc")
	if err := os.WriteFile(cursorPath, []byte(cursorRule(absSpace, opts.Project)), 0o644); err != nil {
		return nil, fmt.Errorf("write cursor rule: %w", err)
	}
	res.Files = append(res.Files, cursorPath)
	log.Info("wrote entry point", "path", cursorPath)

	if !opts.Silent {
		fmt.Fprintf(os.Stdout, "Activated ContextVerse space → %s\n", absSpace)
		for _, f := range res.Files {
			fmt.Fprintf(os.Stdout, "  ✅ %s\n", f)
		}
		if opts.Project != "" {
			fmt.Fprintf(os.Stdout, "  project: %s\n", opts.Project)
		}
	}
	return res, nil
}

func claudeMD(spaceRoot, project string) string {
	var b strings.Builder
	b.WriteString("<!-- CLAUDE.md — auto-generated by contextd. Do not edit. -->\n")
	b.WriteString("<!-- Run: contextd activate to refresh -->\n\n")
	b.WriteString("# Context\n\n")
	b.WriteString(fmt.Sprintf("Source of truth: `%s`\n\n", spaceRoot))
	b.WriteString("Read these files in order:\n")
	b.WriteString(fmt.Sprintf("1. `%s/context-entry.md` — routing\n", spaceRoot))
	b.WriteString(fmt.Sprintf("2. `%s/identity/me.md` — who you're talking to\n", spaceRoot))
	b.WriteString(fmt.Sprintf("3. `%s/team/principles.md` — how we work\n", spaceRoot))
	b.WriteString(fmt.Sprintf("4. `%s/space-index.md` — what exists\n", spaceRoot))
	b.WriteString(fmt.Sprintf("5. `%s/decisions.md` — key decisions\n", spaceRoot))
	if project != "" {
		b.WriteString(fmt.Sprintf("6. `%s/projects/%s/project.md` — this project\n", spaceRoot, project))
	} else {
		b.WriteString(fmt.Sprintf("6. `%s/projects/<relevant>/` — project context for the current task\n", spaceRoot))
	}
	b.WriteString("\n## Rules\n")
	b.WriteString("- Follow importance weights from principles.md\n")
	b.WriteString("- Check space-index.md before searching\n")
	b.WriteString(fmt.Sprintf("- Never modify `%s/identity/` without explicit permission\n", spaceRoot))
	return b.String()
}

func cursorRule(spaceRoot, project string) string {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("description: ContextVerse portable context — read the space before acting\n")
	b.WriteString("alwaysApply: true\n")
	b.WriteString("---\n\n")
	b.WriteString("<!-- auto-generated by contextd. Do not edit. Run: contextd activate -->\n\n")
	b.WriteString("# ContextVerse\n\n")
	b.WriteString(fmt.Sprintf("Source of truth: `%s`\n\n", spaceRoot))
	b.WriteString("Before answering project questions, read:\n")
	b.WriteString(fmt.Sprintf("1. `%s/context-entry.md`\n", spaceRoot))
	b.WriteString(fmt.Sprintf("2. `%s/identity/me.md`\n", spaceRoot))
	b.WriteString(fmt.Sprintf("3. `%s/team/principles.md`\n", spaceRoot))
	b.WriteString(fmt.Sprintf("4. `%s/space-index.md`\n", spaceRoot))
	b.WriteString(fmt.Sprintf("5. `%s/decisions.md`\n", spaceRoot))
	if project != "" {
		b.WriteString(fmt.Sprintf("6. `%s/projects/%s/project.md`\n", spaceRoot, project))
	}
	b.WriteString("\nDo not modify identity files without explicit user permission.\n")
	return b.String()
}
