package export

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Single renders the same documents as ChatGPT does, concatenated into one
// Markdown file.
//
// The folder export exists for ChatGPT's Knowledge upload, which takes files.
// Everything else — a chat box, a UI with one context field, a colleague asking
// what your setup is — wants a single document, and until now the answer was to
// cat five files together by hand.
//
// Missing sources are named in the output rather than skipped silently: a
// context pack that is quietly missing your principles is worse than one that
// says so.
func Single(spaceRoot, project string) (string, *Result, error) {
	if spaceRoot == "" {
		return "", nil, fmt.Errorf("space root required")
	}
	res := &Result{}
	var b strings.Builder

	b.WriteString("# Context pack\n\n")
	b.WriteString("_Generated by contextd. Everything below was written by hand; nothing is inferred._\n")

	for _, f := range ChatGPTFiles(project) {
		rel := f.Rel
		raw, err := os.ReadFile(filepath.Join(spaceRoot, filepath.FromSlash(rel)))
		b.WriteString("\n---\n\n## " + rel + "\n\n")
		if err != nil {
			res.Missing = append(res.Missing, rel)
			b.WriteString("_(missing from this space)_\n")
			continue
		}
		res.Written = append(res.Written, rel)
		body := strings.TrimRight(string(raw), "\n")
		// Demote headings by one level so the document has a single h1 and the
		// sources keep their structure underneath it.
		var lines []string
		for _, line := range strings.Split(body, "\n") {
			if strings.HasPrefix(line, "#") {
				line = "#" + line
			}
			lines = append(lines, line)
		}
		b.WriteString(strings.Join(lines, "\n"))
		b.WriteString("\n")
	}
	return b.String(), res, nil
}
