package graph

import (
	"fmt"
	"path"
	"sort"
	"strings"
	"time"
)

// Rendering the graph for three audiences: the space's own index files, and the
// AI at session start.

// approxTokens is a deliberately crude estimate — roughly four characters per
// token for English prose. Exact counting would need a tokenizer per model and
// would still be wrong for the next one; the budget only has to stop the map
// from growing without bound.
func approxTokens(s string) int { return len(s) / 4 }

// MapOptions controls the session-start map.
type MapOptions struct {
	Project   string // the project the session is working in, if any
	Budget    int    // approximate tokens; 0 means 700
	SpaceRoot string
}

// RenderMap produces the token-budgeted map handed to an AI at session start:
// the shape of the space and how to fetch any of it, rather than the space
// itself.
//
// This is the alternative arm of the eager-vs-lazy question, not a replacement
// for the entry set. Which one a model actually does better with has not been
// measured, and switching the default on an unmeasured belief is the mistake
// this whole line of work exists to avoid.
func RenderMap(g *Graph, opts MapOptions) string {
	if opts.Budget <= 0 {
		opts.Budget = 700
	}
	var b strings.Builder

	fmt.Fprintf(&b, "# Context map\n\n")
	fmt.Fprintf(&b, "%d documents", len(g.Nodes))
	if projects := g.projects(); len(projects) > 0 {
		fmt.Fprintf(&b, " · %d projects", len(projects))
	}
	fmt.Fprintf(&b, ". You are given the map, not the contents — fetch what you need:\n\n")
	fmt.Fprintf(&b, "    contextd file get <path>       read a document\n")
	fmt.Fprintf(&b, "    contextd search <query>        find where something is written\n")
	fmt.Fprintf(&b, "    contextd graph <path>          what links to a document\n\n")

	// The entry point first: it is the front door by design, whatever its rank.
	if n, ok := g.Node("context-entry.md"); ok {
		fmt.Fprintf(&b, "Start at `%s` — %s\n\n", n.Path, describe(n))
	}

	fmt.Fprintf(&b, "## Most referenced\n\n")
	written := 0
	for _, n := range g.Nodes {
		if n.Path == "context-entry.md" {
			continue
		}
		if opts.Project != "" && n.Project != "" && n.Project != opts.Project {
			continue // another project's detail is noise for this session
		}
		line := fmt.Sprintf("- `%s` — %s\n", n.Path, describe(n))
		if approxTokens(b.String())+approxTokens(line) > opts.Budget {
			break
		}
		b.WriteString(line)
		written++
	}
	if written == 0 {
		b.WriteString("- (the space has no documents yet)\n")
	}

	if opts.Project != "" {
		if local := g.projectNeighbourhood(opts.Project); len(local) > 0 {
			fmt.Fprintf(&b, "\n## This project: %s\n\n", opts.Project)
			for _, p := range local {
				n, _ := g.Node(p)
				line := fmt.Sprintf("- `%s` — %s\n", p, describe(n))
				if approxTokens(b.String())+approxTokens(line) > opts.Budget {
					break
				}
				b.WriteString(line)
			}
		}
	}

	if stale := g.staleNodes(); len(stale) > 0 {
		fmt.Fprintf(&b, "\n⚠ %d document(s) are past their review date and may be wrong: %s\n",
			len(stale), strings.Join(truncate(stale, 5), ", "))
	}

	return b.String()
}

func describe(n Node) string {
	parts := []string{}
	if n.Title != "" && n.Title != strings.TrimSuffix(path.Base(n.Path), path.Ext(n.Path)) {
		parts = append(parts, n.Title)
	}
	if n.InDegree > 0 {
		parts = append(parts, fmt.Sprintf("%d references", n.InDegree))
	}
	if n.Stale {
		parts = append(parts, "stale")
	}
	if len(parts) == 0 {
		return n.Title
	}
	return strings.Join(parts, ", ")
}

func truncate(s []string, n int) []string {
	if len(s) <= n {
		return s
	}
	return append(s[:n:n], "…")
}

func (g *Graph) projects() []string {
	seen := map[string]bool{}
	var out []string
	for _, n := range g.Nodes {
		if n.Project != "" && !seen[n.Project] {
			seen[n.Project] = true
			out = append(out, n.Project)
		}
	}
	sort.Strings(out)
	return out
}

func (g *Graph) projectNeighbourhood(project string) []string {
	var out []string
	for _, n := range g.Nodes {
		if n.Project == project {
			out = append(out, n.Path)
		}
	}
	sort.Strings(out)
	return out
}

func (g *Graph) staleNodes() []string {
	var out []string
	for _, n := range g.Nodes {
		if n.Stale {
			out = append(out, n.Path)
		}
	}
	sort.Strings(out)
	return out
}

// RenderIndex produces space-index.md from the graph.
//
// The previous version was a hardcoded format string: it listed the directory
// names under projects/ and filled Owner and Dependencies with em dashes, while
// context-entry.md told every AI to read it for "what exists". This one can
// answer that.
func RenderIndex(g *Graph, now time.Time) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# Space Index\n\n")
	fmt.Fprintf(&b, "_Generated by `contextd index update` from the links in this space. %s._\n\n", now.Format("2006-01-02"))
	fmt.Fprintf(&b, "%s\n\n", g.Summary())

	projects := g.projects()
	fmt.Fprintf(&b, "## Projects\n\n")
	if len(projects) == 0 {
		fmt.Fprintf(&b, "_None yet._\n\n")
	} else {
		fmt.Fprintf(&b, "| Project | Documents | Owner | References out | Stale |\n")
		fmt.Fprintf(&b, "|---|---|---|---|---|\n")
		for _, p := range projects {
			docs, owner, refs, stale := 0, "", 0, 0
			for _, n := range g.Nodes {
				if n.Project != p {
					continue
				}
				docs++
				refs += n.OutDegree
				if n.Stale {
					stale++
				}
				if owner == "" && n.Owner != "" {
					owner = n.Owner
				}
			}
			if owner == "" {
				owner = "—"
			}
			staleCell := "—"
			if stale > 0 {
				staleCell = fmt.Sprintf("%d", stale)
			}
			fmt.Fprintf(&b, "| %s | %d | %s | %d | %s |\n", p, docs, owner, refs, staleCell)
		}
		fmt.Fprintf(&b, "\n")
	}

	fmt.Fprintf(&b, "## Most referenced\n\n")
	shown := 0
	for _, n := range g.Nodes {
		if shown >= 15 {
			break
		}
		if n.InDegree == 0 {
			continue
		}
		fmt.Fprintf(&b, "- `%s` — %s (%d references)\n", n.Path, n.Title, n.InDegree)
		shown++
	}
	if shown == 0 {
		fmt.Fprintf(&b, "_Nothing links to anything yet._\n")
	}

	if len(g.Orphans) > 0 {
		fmt.Fprintf(&b, "\n## Nothing links here\n\n")
		for _, o := range truncate(g.Orphans, 15) {
			fmt.Fprintf(&b, "- `%s`\n", o)
		}
	}
	if len(g.Broken) > 0 {
		fmt.Fprintf(&b, "\n## Broken links\n\n")
		for _, e := range g.Broken {
			if len(strings.Split(b.String(), "\n")) > 400 {
				break
			}
			fmt.Fprintf(&b, "- `%s:%d` → `%s`\n", e.From, e.Line, e.Raw)
		}
	}
	return b.String()
}

// RenderSpaceMap produces team/space-map.md: the shape of the space, drawn from
// what is actually in it rather than from a drawing seeded once at init.
func RenderSpaceMap(g *Graph, now time.Time) string {
	var b strings.Builder
	fmt.Fprintf(&b, "---\nlast-validated: %s\nstale-after: 90d\n---\n\n", now.Format("2006-01-02"))
	fmt.Fprintf(&b, "# Space Map\n\n")
	fmt.Fprintf(&b, "_Generated from this space's own links. Edit the documents, not this file._\n\n")

	// Group by top-level directory so the shape is visible at a glance.
	groups := map[string][]Node{}
	var order []string
	for _, n := range g.Nodes {
		dir := path.Dir(n.Path)
		if dir == "." {
			dir = "(root)"
		}
		if _, ok := groups[dir]; !ok {
			order = append(order, dir)
		}
		groups[dir] = append(groups[dir], n)
	}
	sort.Strings(order)

	for _, dir := range order {
		fmt.Fprintf(&b, "## %s\n\n", dir)
		nodes := groups[dir]
		sort.Slice(nodes, func(i, j int) bool { return nodes[i].Path < nodes[j].Path })
		for _, n := range nodes {
			marks := ""
			if n.Stale {
				marks = " ⚠ past review date"
			}
			fmt.Fprintf(&b, "- `%s` — %s%s\n", path.Base(n.Path), describe(n), marks)
		}
		fmt.Fprintf(&b, "\n")
	}
	return b.String()
}

// Mermaid renders the top-ranked slice of the graph as a diagram source.
//
// Deliberately a slice: a whole graph of any size renders as an unreadable
// hairball, and a picture nobody can read is worse than a list.
func Mermaid(g *Graph, limit int) string {
	if limit <= 0 || limit > len(g.Nodes) {
		limit = len(g.Nodes)
	}
	keep := map[string]string{}
	for i, n := range g.Nodes[:limit] {
		keep[n.Path] = fmt.Sprintf("n%d", i)
	}

	var b strings.Builder
	b.WriteString("graph LR\n")

	paths := make([]string, 0, len(keep))
	for p := range keep {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		node, _ := g.Node(p)
		label := node.Title
		if label == "" {
			label = p
		}
		label = strings.ReplaceAll(label, `"`, "'")
		fmt.Fprintf(&b, "  %s[\"%s\"]\n", keep[p], label)
	}
	for _, e := range g.Edges {
		if e.Broken || e.Code {
			continue
		}
		from, okF := keep[e.From]
		to, okT := keep[e.To]
		if !okF || !okT || from == to {
			continue
		}
		fmt.Fprintf(&b, "  %s --> %s\n", from, to)
	}
	return b.String()
}
